services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME:-app}
    environment:
      # FastAPI + Alembic read this
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@postgres:5432/postgres}
    ports:
      - "${HOST_PORT:-80}:80"        # SPA + /api proxy
      - "${HOST_PORT_API:-2022}:2022" # optional: direct API access
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgres:
    image: postgres:17-alpine3.21
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
