from typing import Protocol


class ApplicationBase(Protocol):
    @property
    def current_state(self) -> str: ...
    @property
    def state_output(self) -> dict: ...
    @property
    def is_completed(self) -> bool: ...
    def maybe_error(self) -> str | None: ...
